language: bash

services:
  - docker

before_install:
  - docker build -t reverseproxy  ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed 01065450079/reverseproxy:v2
  - docker tag udagram-api-feed 01065450079/udagram-api-user:v2
  - docker tag udagram-api-feed 01065450079/udagram-api-feed:v2
  - docker tag udagram-api-feed 01065450079/udagram-frontend:v2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 01065450079/reverseproxy:v1
  - docker push 01065450079/udagram-api-user:v1
  - docker push 01065450079/udagram-api-feed:v1
  - docker push 01065450079/udagram-frontend:v1
